Non-substantive changes per recommendations
timdows/MMM-JsonTable pull request #95
Opened 2024-03-25 16:53 UTC by dathbe

Non-substantive changes as recommended here https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md#MMM-JsonTable-by-timdows

I have tested this, though I'm not sure my non-dev production installation is using `eslint-plugin-json`, which is changed to `eslint-plugin-jsonc` (latest version per the documentation I found) in this PR.

They also recommend creating a "flat" eslint config, which I know nothing about, and changing the primary branch name to `main`, which I can't do in a PR.

2024-03-25 23:05 UTC, KristjanESPERANTO requested changes

2024-03-25 23:05 UTC, KristjanESPERANTO commented on package.json
> +    "eslint-plugin-jsonc": "^2.14.1",
Replacing the plugin is a good thing, but would also require a change in the ESLint configuration.

I see two options here:

1. adjust the ESLint configuration accordingly. Or
2. undo the change and we address this in a new PR. As I also like and use this module, I am quite willing to do this :slightly_smiling_face:

2024-03-26 01:26 UTC, dathbe commented
I'll close and let you deal with ESLint.  Once you have the ESLint tutorial up, I may try to tackle it.  But I'm not very good with javascript, so I definitely don't know how to check it with ESLint.

2024-03-26 15:07 UTC, dathbe commented
Reopening with the jsonc change backed out.  The others should be fine.

2024-03-26 17:39 UTC, KristjanESPERANTO approved these changes

2024-04-01 19:41 UTC, merged